services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn basic_project.basic_project.wsgi:application
    workingDir: basic_project
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: basic_project.settings
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: "False"
